void  print_alphabet(void);
void print_alphabet_x10(void);
int _islower(int n);
int _putchar(char c);
int _isalpha(int c);
int _putchar(char c);
int print_sign(int n);
int _abs(int);
void positive_or_negative(int i); 
int largest_number(int a, int b, int c);